QTDIR=/usr/lib/qt-3.3
#############################################################################
# Makefile for building: mysqlcc
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Tue Jul 26 06:19:08 2011
# Project:  mysqlcc.pro
# Template: app
# Command: $(QMAKE) -o Makefile mysqlcc.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_REENTRANT  -DQT_DLL -DHAVE_MYSQLCC_CONFIG -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -D_REENTRANT  -DQT_DLL -DHAVE_MYSQLCC_CONFIG -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3/mkspecs/default -I. -Iinclude -Ishared/include -Iinclude/CSqlEditor -I/usr/include/mysql -I$(QTDIR)/include -Imoc/
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib /usr/lib/mysql/libmysqlclient.so -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = tmp/

####### Files

HEADERS = include/CAboutBox.h \
		include/CAdministrationWindow.h \
		include/CAppConfigDialog.h \
		include/CApplication.h \
		include/CConfigDialog.h \
		include/CConsoleWindow.h \
		include/CCreditsBox.h \
		include/CDatabaseGroupItem.h \
		include/CDatabaseItem.h \
		include/CDatabaseListView.h \
		include/CDatabaseListViewItem.h \
		include/CDockWindow.h \
		include/CFieldEditorWidget.h \
		include/CFieldEditorWindow.h \
		include/CHistoryView.h \
		include/CHotKeyEditorDialog.h \
		include/CImageViewer.h \
		include/CInfoDialog.h \
		include/CMDIWindow.h \
		include/CMySQLServer.h \
		include/CMyWindow.h \
		include/CPlugin.h \
		include/CPluginWindow.h \
		include/CProperties.h \
		include/CQueryTable.h \
		include/CQueryWindow.h \
		include/CQueryWindowOptionsDialog.h \
		include/CRegisterServerDialog.h \
		include/CServerAdministrationItem.h \
		include/CServerItem.h \
		include/CShowDatabaseGroupProperties.h \
		include/CShowServerProperties.h \
		include/CShowTableGroupProperties.h \
		include/CShowTableProperties.h \
		include/CSqlEditorFont.h \
		include/CSqlTable.h \
		include/CTable.h \
		include/CTableFieldChooser.h \
		include/CTableGroupItem.h \
		include/CTableItem.h \
		include/CTableProperties.h \
		include/CTableSpecific.h \
		include/CTableTools.h \
		include/CTableWindow.h \
		include/CTablesListBox.h \
		include/CTextDialog.h \
		include/CTextFieldEditor.h \
		include/CToolBar.h \
		include/CUserAdminItem.h \
		include/CUserAdminWindow.h \
		include/CUserItem.h \
		include/config.h \
		include/globals.h \
		include/icons.h \
		include/mysqlcc_main.h \
		include/panels.h \
		include/resource.h \
		include/shared_menus.h \
		include/CSqlEditor/CSqlEditor.h \
		include/CSqlEditor/completion.h \
		include/CSqlEditor/editor.h \
		include/CSqlEditor/paragdata.h \
		include/CSqlEditor/parenmatcher.h \
		include/CSqlEditor/sqlcompletion.h \
		include/CSqlEditor/syntaxhighliter_sql.h \
		shared/include/CAction.h \
		shared/include/CConfig.h \
		shared/include/CMySQL.h \
		shared/include/CMySQLCCPlugin.h \
		shared/include/CMySQLQuery.h \
		shared/include/CNullLineEdit.h \
		shared/include/CSqlTableItem.h \
		shared/include/shared.h
SOURCES = src/CAboutBox.cpp \
		src/CAdministrationWindow.cpp \
		src/CAppConfigDialog.cpp \
		src/CApplication.cpp \
		src/CConfigDialog.cpp \
		src/CConsoleWindow.cpp \
		src/CCreditsBox.cpp \
		src/CDatabaseGroupItem.cpp \
		src/CDatabaseItem.cpp \
		src/CDatabaseListView.cpp \
		src/CDatabaseListViewItem.cpp \
		src/CDockWindow.cpp \
		src/CFieldEditorWidget.cpp \
		src/CFieldEditorWindow.cpp \
		src/CHistoryView.cpp \
		src/CHotKeyEditorDialog.cpp \
		src/CImageViewer.cpp \
		src/CInfoDialog.cpp \
		src/CMDIWindow.cpp \
		src/CMySQLServer.cpp \
		src/CMyWindow.cpp \
		src/CPlugin.cpp \
		src/CPluginWindow.cpp \
		src/CProperties.cpp \
		src/CQueryTable.cpp \
		src/CQueryWindow.cpp \
		src/CQueryWindowOptionsDialog.cpp \
		src/CRegisterServerDialog.cpp \
		src/CServerAdministrationItem.cpp \
		src/CServerItem.cpp \
		src/CShowDatabaseGroupProperties.cpp \
		src/CShowServerProperties.cpp \
		src/CShowTableGroupProperties.cpp \
		src/CShowTableProperties.cpp \
		src/CSqlEditorFont.cpp \
		src/CSqlTable.cpp \
		src/CTable.cpp \
		src/CTableFieldChooser.cpp \
		src/CTableGroupItem.cpp \
		src/CTableItem.cpp \
		src/CTableProperties.cpp \
		src/CTableSpecific.cpp \
		src/CTableTools.cpp \
		src/CTableWindow.cpp \
		src/CTablesListBox.cpp \
		src/CTextDialog.cpp \
		src/CTextFieldEditor.cpp \
		src/CToolBar.cpp \
		src/CUserAdminItem.cpp \
		src/CUserAdminWindow.cpp \
		src/CUserItem.cpp \
		src/globals.cpp \
		src/main.cpp \
		src/mysqlcc_main.cpp \
		src/panels.cpp \
		src/shared_menus.cpp \
		src/CSqlEditor/CSqlEditor.cpp \
		src/CSqlEditor/completion.cpp \
		src/CSqlEditor/editor.cpp \
		src/CSqlEditor/parenmatcher.cpp \
		src/CSqlEditor/sqlcompletion.cpp \
		src/CSqlEditor/syntaxhighliter_sql.cpp \
		shared/src/CAction.cpp \
		shared/src/CConfig.cpp \
		shared/src/CMySQL.cpp \
		shared/src/CMySQLQuery.cpp \
		shared/src/CNullLineEdit.cpp \
		shared/src/CSqlTableItem.cpp \
		shared/src/shared.cpp
OBJECTS = tmp/CAboutBox.o \
		tmp/CAdministrationWindow.o \
		tmp/CAppConfigDialog.o \
		tmp/CApplication.o \
		tmp/CConfigDialog.o \
		tmp/CConsoleWindow.o \
		tmp/CCreditsBox.o \
		tmp/CDatabaseGroupItem.o \
		tmp/CDatabaseItem.o \
		tmp/CDatabaseListView.o \
		tmp/CDatabaseListViewItem.o \
		tmp/CDockWindow.o \
		tmp/CFieldEditorWidget.o \
		tmp/CFieldEditorWindow.o \
		tmp/CHistoryView.o \
		tmp/CHotKeyEditorDialog.o \
		tmp/CImageViewer.o \
		tmp/CInfoDialog.o \
		tmp/CMDIWindow.o \
		tmp/CMySQLServer.o \
		tmp/CMyWindow.o \
		tmp/CPlugin.o \
		tmp/CPluginWindow.o \
		tmp/CProperties.o \
		tmp/CQueryTable.o \
		tmp/CQueryWindow.o \
		tmp/CQueryWindowOptionsDialog.o \
		tmp/CRegisterServerDialog.o \
		tmp/CServerAdministrationItem.o \
		tmp/CServerItem.o \
		tmp/CShowDatabaseGroupProperties.o \
		tmp/CShowServerProperties.o \
		tmp/CShowTableGroupProperties.o \
		tmp/CShowTableProperties.o \
		tmp/CSqlEditorFont.o \
		tmp/CSqlTable.o \
		tmp/CTable.o \
		tmp/CTableFieldChooser.o \
		tmp/CTableGroupItem.o \
		tmp/CTableItem.o \
		tmp/CTableProperties.o \
		tmp/CTableSpecific.o \
		tmp/CTableTools.o \
		tmp/CTableWindow.o \
		tmp/CTablesListBox.o \
		tmp/CTextDialog.o \
		tmp/CTextFieldEditor.o \
		tmp/CToolBar.o \
		tmp/CUserAdminItem.o \
		tmp/CUserAdminWindow.o \
		tmp/CUserItem.o \
		tmp/globals.o \
		tmp/main.o \
		tmp/mysqlcc_main.o \
		tmp/panels.o \
		tmp/shared_menus.o \
		tmp/CSqlEditor.o \
		tmp/completion.o \
		tmp/editor.o \
		tmp/parenmatcher.o \
		tmp/sqlcompletion.o \
		tmp/syntaxhighliter_sql.o \
		tmp/CAction.o \
		tmp/CConfig.o \
		tmp/CMySQL.o \
		tmp/CMySQLQuery.o \
		tmp/CNullLineEdit.o \
		tmp/CSqlTableItem.o \
		tmp/shared.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc/moc_CAboutBox.cpp \
		moc/moc_CAdministrationWindow.cpp \
		moc/moc_CAppConfigDialog.cpp \
		moc/moc_CApplication.cpp \
		moc/moc_CConfigDialog.cpp \
		moc/moc_CConsoleWindow.cpp \
		moc/moc_CCreditsBox.cpp \
		moc/moc_CDatabaseGroupItem.cpp \
		moc/moc_CDatabaseItem.cpp \
		moc/moc_CDatabaseListView.cpp \
		moc/moc_CDatabaseListViewItem.cpp \
		moc/moc_CDockWindow.cpp \
		moc/moc_CFieldEditorWidget.cpp \
		moc/moc_CFieldEditorWindow.cpp \
		moc/moc_CHotKeyEditorDialog.cpp \
		moc/moc_CImageViewer.cpp \
		moc/moc_CInfoDialog.cpp \
		moc/moc_CMDIWindow.cpp \
		moc/moc_CMySQLServer.cpp \
		moc/moc_CMyWindow.cpp \
		moc/moc_CPluginWindow.cpp \
		moc/moc_CProperties.cpp \
		moc/moc_CQueryTable.cpp \
		moc/moc_CQueryWindow.cpp \
		moc/moc_CQueryWindowOptionsDialog.cpp \
		moc/moc_CRegisterServerDialog.cpp \
		moc/moc_CServerAdministrationItem.cpp \
		moc/moc_CServerItem.cpp \
		moc/moc_CShowDatabaseGroupProperties.cpp \
		moc/moc_CShowServerProperties.cpp \
		moc/moc_CShowTableGroupProperties.cpp \
		moc/moc_CShowTableProperties.cpp \
		moc/moc_CSqlTable.cpp \
		moc/moc_CTable.cpp \
		moc/moc_CTableFieldChooser.cpp \
		moc/moc_CTableGroupItem.cpp \
		moc/moc_CTableItem.cpp \
		moc/moc_CTableProperties.cpp \
		moc/moc_CTableTools.cpp \
		moc/moc_CTableWindow.cpp \
		moc/moc_CTablesListBox.cpp \
		moc/moc_CTextDialog.cpp \
		moc/moc_CTextFieldEditor.cpp \
		moc/moc_CToolBar.cpp \
		moc/moc_CUserAdminItem.cpp \
		moc/moc_CUserAdminWindow.cpp \
		moc/moc_CUserItem.cpp \
		moc/moc_panels.cpp \
		moc/moc_shared_menus.cpp \
		moc/moc_CSqlEditor.cpp \
		moc/moc_completion.cpp \
		moc/moc_editor.cpp \
		moc/moc_sqlcompletion.cpp \
		moc/moc_CAction.cpp \
		moc/moc_CMySQL.cpp \
		moc/moc_CMySQLCCPlugin.cpp \
		moc/moc_CMySQLQuery.cpp \
		moc/moc_CNullLineEdit.cpp
OBJMOC = tmp/moc_CAboutBox.o \
		tmp/moc_CAdministrationWindow.o \
		tmp/moc_CAppConfigDialog.o \
		tmp/moc_CApplication.o \
		tmp/moc_CConfigDialog.o \
		tmp/moc_CConsoleWindow.o \
		tmp/moc_CCreditsBox.o \
		tmp/moc_CDatabaseGroupItem.o \
		tmp/moc_CDatabaseItem.o \
		tmp/moc_CDatabaseListView.o \
		tmp/moc_CDatabaseListViewItem.o \
		tmp/moc_CDockWindow.o \
		tmp/moc_CFieldEditorWidget.o \
		tmp/moc_CFieldEditorWindow.o \
		tmp/moc_CHotKeyEditorDialog.o \
		tmp/moc_CImageViewer.o \
		tmp/moc_CInfoDialog.o \
		tmp/moc_CMDIWindow.o \
		tmp/moc_CMySQLServer.o \
		tmp/moc_CMyWindow.o \
		tmp/moc_CPluginWindow.o \
		tmp/moc_CProperties.o \
		tmp/moc_CQueryTable.o \
		tmp/moc_CQueryWindow.o \
		tmp/moc_CQueryWindowOptionsDialog.o \
		tmp/moc_CRegisterServerDialog.o \
		tmp/moc_CServerAdministrationItem.o \
		tmp/moc_CServerItem.o \
		tmp/moc_CShowDatabaseGroupProperties.o \
		tmp/moc_CShowServerProperties.o \
		tmp/moc_CShowTableGroupProperties.o \
		tmp/moc_CShowTableProperties.o \
		tmp/moc_CSqlTable.o \
		tmp/moc_CTable.o \
		tmp/moc_CTableFieldChooser.o \
		tmp/moc_CTableGroupItem.o \
		tmp/moc_CTableItem.o \
		tmp/moc_CTableProperties.o \
		tmp/moc_CTableTools.o \
		tmp/moc_CTableWindow.o \
		tmp/moc_CTablesListBox.o \
		tmp/moc_CTextDialog.o \
		tmp/moc_CTextFieldEditor.o \
		tmp/moc_CToolBar.o \
		tmp/moc_CUserAdminItem.o \
		tmp/moc_CUserAdminWindow.o \
		tmp/moc_CUserItem.o \
		tmp/moc_panels.o \
		tmp/moc_shared_menus.o \
		tmp/moc_CSqlEditor.o \
		tmp/moc_completion.o \
		tmp/moc_editor.o \
		tmp/moc_sqlcompletion.o \
		tmp/moc_CAction.o \
		tmp/moc_CMySQL.o \
		tmp/moc_CMySQLCCPlugin.o \
		tmp/moc_CMySQLQuery.o \
		tmp/moc_CNullLineEdit.o
DIST	   = mysqlcc.pro
QMAKE_TARGET = mysqlcc
DESTDIR  = 
TARGET   = mysqlcc

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: mysqlcc.pro  /usr/lib/qt-3.3/mkspecs/default/qmake.conf /usr/lib/qt-3.3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile mysqlcc.pro
qmake: 
	@$(QMAKE) -o Makefile mysqlcc.pro

dist: 
	@mkdir -p tmp/mysqlcc && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) tmp/mysqlcc/ && $(COPY_FILE) --parents translations/Deutsch.ts translations/French.ts translations/Italian.ts translations/Polish.ts translations/Russian.ts translations/Simplified_Chinese.ts translations/Spanish.ts translations/Traditional_Chinese.ts tmp/mysqlcc/ && ( cd `dirname tmp/mysqlcc` && $(TAR) mysqlcc.tar mysqlcc && $(GZIP) mysqlcc.tar ) && $(MOVE) `dirname tmp/mysqlcc`/mysqlcc.tar.gz . && $(DEL_FILE) -r tmp/mysqlcc

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

tmp/CAboutBox.o: src/CAboutBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CAboutBox.o src/CAboutBox.cpp

tmp/CAdministrationWindow.o: src/CAdministrationWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CAdministrationWindow.o src/CAdministrationWindow.cpp

tmp/CAppConfigDialog.o: src/CAppConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CAppConfigDialog.o src/CAppConfigDialog.cpp

tmp/CApplication.o: src/CApplication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CApplication.o src/CApplication.cpp

tmp/CConfigDialog.o: src/CConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CConfigDialog.o src/CConfigDialog.cpp

tmp/CConsoleWindow.o: src/CConsoleWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CConsoleWindow.o src/CConsoleWindow.cpp

tmp/CCreditsBox.o: src/CCreditsBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CCreditsBox.o src/CCreditsBox.cpp

tmp/CDatabaseGroupItem.o: src/CDatabaseGroupItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CDatabaseGroupItem.o src/CDatabaseGroupItem.cpp

tmp/CDatabaseItem.o: src/CDatabaseItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CDatabaseItem.o src/CDatabaseItem.cpp

tmp/CDatabaseListView.o: src/CDatabaseListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CDatabaseListView.o src/CDatabaseListView.cpp

tmp/CDatabaseListViewItem.o: src/CDatabaseListViewItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CDatabaseListViewItem.o src/CDatabaseListViewItem.cpp

tmp/CDockWindow.o: src/CDockWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CDockWindow.o src/CDockWindow.cpp

tmp/CFieldEditorWidget.o: src/CFieldEditorWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CFieldEditorWidget.o src/CFieldEditorWidget.cpp

tmp/CFieldEditorWindow.o: src/CFieldEditorWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CFieldEditorWindow.o src/CFieldEditorWindow.cpp

tmp/CHistoryView.o: src/CHistoryView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CHistoryView.o src/CHistoryView.cpp

tmp/CHotKeyEditorDialog.o: src/CHotKeyEditorDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CHotKeyEditorDialog.o src/CHotKeyEditorDialog.cpp

tmp/CImageViewer.o: src/CImageViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CImageViewer.o src/CImageViewer.cpp

tmp/CInfoDialog.o: src/CInfoDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CInfoDialog.o src/CInfoDialog.cpp

tmp/CMDIWindow.o: src/CMDIWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CMDIWindow.o src/CMDIWindow.cpp

tmp/CMySQLServer.o: src/CMySQLServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CMySQLServer.o src/CMySQLServer.cpp

tmp/CMyWindow.o: src/CMyWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CMyWindow.o src/CMyWindow.cpp

tmp/CPlugin.o: src/CPlugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CPlugin.o src/CPlugin.cpp

tmp/CPluginWindow.o: src/CPluginWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CPluginWindow.o src/CPluginWindow.cpp

tmp/CProperties.o: src/CProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CProperties.o src/CProperties.cpp

tmp/CQueryTable.o: src/CQueryTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CQueryTable.o src/CQueryTable.cpp

tmp/CQueryWindow.o: src/CQueryWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CQueryWindow.o src/CQueryWindow.cpp

tmp/CQueryWindowOptionsDialog.o: src/CQueryWindowOptionsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CQueryWindowOptionsDialog.o src/CQueryWindowOptionsDialog.cpp

tmp/CRegisterServerDialog.o: src/CRegisterServerDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CRegisterServerDialog.o src/CRegisterServerDialog.cpp

tmp/CServerAdministrationItem.o: src/CServerAdministrationItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CServerAdministrationItem.o src/CServerAdministrationItem.cpp

tmp/CServerItem.o: src/CServerItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CServerItem.o src/CServerItem.cpp

tmp/CShowDatabaseGroupProperties.o: src/CShowDatabaseGroupProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CShowDatabaseGroupProperties.o src/CShowDatabaseGroupProperties.cpp

tmp/CShowServerProperties.o: src/CShowServerProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CShowServerProperties.o src/CShowServerProperties.cpp

tmp/CShowTableGroupProperties.o: src/CShowTableGroupProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CShowTableGroupProperties.o src/CShowTableGroupProperties.cpp

tmp/CShowTableProperties.o: src/CShowTableProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CShowTableProperties.o src/CShowTableProperties.cpp

tmp/CSqlEditorFont.o: src/CSqlEditorFont.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CSqlEditorFont.o src/CSqlEditorFont.cpp

tmp/CSqlTable.o: src/CSqlTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CSqlTable.o src/CSqlTable.cpp

tmp/CTable.o: src/CTable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTable.o src/CTable.cpp

tmp/CTableFieldChooser.o: src/CTableFieldChooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableFieldChooser.o src/CTableFieldChooser.cpp

tmp/CTableGroupItem.o: src/CTableGroupItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableGroupItem.o src/CTableGroupItem.cpp

tmp/CTableItem.o: src/CTableItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableItem.o src/CTableItem.cpp

tmp/CTableProperties.o: src/CTableProperties.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableProperties.o src/CTableProperties.cpp

tmp/CTableSpecific.o: src/CTableSpecific.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableSpecific.o src/CTableSpecific.cpp

tmp/CTableTools.o: src/CTableTools.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableTools.o src/CTableTools.cpp

tmp/CTableWindow.o: src/CTableWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTableWindow.o src/CTableWindow.cpp

tmp/CTablesListBox.o: src/CTablesListBox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTablesListBox.o src/CTablesListBox.cpp

tmp/CTextDialog.o: src/CTextDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTextDialog.o src/CTextDialog.cpp

tmp/CTextFieldEditor.o: src/CTextFieldEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CTextFieldEditor.o src/CTextFieldEditor.cpp

tmp/CToolBar.o: src/CToolBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CToolBar.o src/CToolBar.cpp

tmp/CUserAdminItem.o: src/CUserAdminItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CUserAdminItem.o src/CUserAdminItem.cpp

tmp/CUserAdminWindow.o: src/CUserAdminWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CUserAdminWindow.o src/CUserAdminWindow.cpp

tmp/CUserItem.o: src/CUserItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CUserItem.o src/CUserItem.cpp

tmp/globals.o: src/globals.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/globals.o src/globals.cpp

tmp/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/main.o src/main.cpp

tmp/mysqlcc_main.o: src/mysqlcc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/mysqlcc_main.o src/mysqlcc_main.cpp

tmp/panels.o: src/panels.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/panels.o src/panels.cpp

tmp/shared_menus.o: src/shared_menus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/shared_menus.o src/shared_menus.cpp

tmp/CSqlEditor.o: src/CSqlEditor/CSqlEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CSqlEditor.o src/CSqlEditor/CSqlEditor.cpp

tmp/completion.o: src/CSqlEditor/completion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/completion.o src/CSqlEditor/completion.cpp

tmp/editor.o: src/CSqlEditor/editor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/editor.o src/CSqlEditor/editor.cpp

tmp/parenmatcher.o: src/CSqlEditor/parenmatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/parenmatcher.o src/CSqlEditor/parenmatcher.cpp

tmp/sqlcompletion.o: src/CSqlEditor/sqlcompletion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/sqlcompletion.o src/CSqlEditor/sqlcompletion.cpp

tmp/syntaxhighliter_sql.o: src/CSqlEditor/syntaxhighliter_sql.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/syntaxhighliter_sql.o src/CSqlEditor/syntaxhighliter_sql.cpp

tmp/CAction.o: shared/src/CAction.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CAction.o shared/src/CAction.cpp

tmp/CConfig.o: shared/src/CConfig.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CConfig.o shared/src/CConfig.cpp

tmp/CMySQL.o: shared/src/CMySQL.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CMySQL.o shared/src/CMySQL.cpp

tmp/CMySQLQuery.o: shared/src/CMySQLQuery.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CMySQLQuery.o shared/src/CMySQLQuery.cpp

tmp/CNullLineEdit.o: shared/src/CNullLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CNullLineEdit.o shared/src/CNullLineEdit.cpp

tmp/CSqlTableItem.o: shared/src/CSqlTableItem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/CSqlTableItem.o shared/src/CSqlTableItem.cpp

tmp/shared.o: shared/src/shared.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/shared.o shared/src/shared.cpp

tmp/moc_CAboutBox.o: moc/moc_CAboutBox.cpp  include/CAboutBox.h include/CInfoDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CAboutBox.o moc/moc_CAboutBox.cpp

tmp/moc_CAdministrationWindow.o: moc/moc_CAdministrationWindow.cpp  include/CAdministrationWindow.h include/CMyWindow.h \
		include/CProperties.h \
		include/CQueryTable.h \
		include/CTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CAdministrationWindow.o moc/moc_CAdministrationWindow.cpp

tmp/moc_CAppConfigDialog.o: moc/moc_CAppConfigDialog.cpp  include/CAppConfigDialog.h include/CConfigDialog.h \
		include/CSqlEditorFont.h \
		include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CAppConfigDialog.o moc/moc_CAppConfigDialog.cpp

tmp/moc_CApplication.o: moc/moc_CApplication.cpp  include/CApplication.h include/CMyWindow.h \
		include/CPlugin.h \
		include/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CApplication.o moc/moc_CApplication.cpp

tmp/moc_CConfigDialog.o: moc/moc_CConfigDialog.cpp  include/CConfigDialog.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CConfigDialog.o moc/moc_CConfigDialog.cpp

tmp/moc_CConsoleWindow.o: moc/moc_CConsoleWindow.cpp  include/CConsoleWindow.h include/CMyWindow.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CConsoleWindow.o moc/moc_CConsoleWindow.cpp

tmp/moc_CCreditsBox.o: moc/moc_CCreditsBox.cpp  include/CCreditsBox.h include/CInfoDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CCreditsBox.o moc/moc_CCreditsBox.cpp

tmp/moc_CDatabaseGroupItem.o: moc/moc_CDatabaseGroupItem.cpp  include/CDatabaseGroupItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CDatabaseGroupItem.o moc/moc_CDatabaseGroupItem.cpp

tmp/moc_CDatabaseItem.o: moc/moc_CDatabaseItem.cpp  include/CDatabaseItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CDatabaseItem.o moc/moc_CDatabaseItem.cpp

tmp/moc_CDatabaseListView.o: moc/moc_CDatabaseListView.cpp  include/CDatabaseListView.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CDatabaseListView.o moc/moc_CDatabaseListView.cpp

tmp/moc_CDatabaseListViewItem.o: moc/moc_CDatabaseListViewItem.cpp  include/CDatabaseListViewItem.h include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CDatabaseListViewItem.o moc/moc_CDatabaseListViewItem.cpp

tmp/moc_CDockWindow.o: moc/moc_CDockWindow.cpp  include/CDockWindow.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CDockWindow.o moc/moc_CDockWindow.cpp

tmp/moc_CFieldEditorWidget.o: moc/moc_CFieldEditorWidget.cpp  include/CFieldEditorWidget.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CFieldEditorWidget.o moc/moc_CFieldEditorWidget.cpp

tmp/moc_CFieldEditorWindow.o: moc/moc_CFieldEditorWindow.cpp  include/CFieldEditorWindow.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CFieldEditorWindow.o moc/moc_CFieldEditorWindow.cpp

tmp/moc_CHotKeyEditorDialog.o: moc/moc_CHotKeyEditorDialog.cpp  include/CHotKeyEditorDialog.h include/CConfigDialog.h \
		include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CHotKeyEditorDialog.o moc/moc_CHotKeyEditorDialog.cpp

tmp/moc_CImageViewer.o: moc/moc_CImageViewer.cpp  include/CImageViewer.h include/CFieldEditorWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CImageViewer.o moc/moc_CImageViewer.cpp

tmp/moc_CInfoDialog.o: moc/moc_CInfoDialog.cpp  include/CInfoDialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CInfoDialog.o moc/moc_CInfoDialog.cpp

tmp/moc_CMDIWindow.o: moc/moc_CMDIWindow.cpp  include/CMDIWindow.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMDIWindow.o moc/moc_CMDIWindow.cpp

tmp/moc_CMySQLServer.o: moc/moc_CMySQLServer.cpp  include/CMySQLServer.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMySQLServer.o moc/moc_CMySQLServer.cpp

tmp/moc_CMyWindow.o: moc/moc_CMyWindow.cpp  include/CMyWindow.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMyWindow.o moc/moc_CMyWindow.cpp

tmp/moc_CPluginWindow.o: moc/moc_CPluginWindow.cpp  include/CPluginWindow.h include/CMyWindow.h \
		include/CPlugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CPluginWindow.o moc/moc_CPluginWindow.cpp

tmp/moc_CProperties.o: moc/moc_CProperties.cpp  include/CProperties.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CProperties.o moc/moc_CProperties.cpp

tmp/moc_CQueryTable.o: moc/moc_CQueryTable.cpp  include/CQueryTable.h include/CTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CQueryTable.o moc/moc_CQueryTable.cpp

tmp/moc_CQueryWindow.o: moc/moc_CQueryWindow.cpp  include/CQueryWindow.h include/CMyWindow.h \
		include/config.h \
		include/CQueryWindowOptionsDialog.h \
		include/CTable.h \
		include/CConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CQueryWindow.o moc/moc_CQueryWindow.cpp

tmp/moc_CQueryWindowOptionsDialog.o: moc/moc_CQueryWindowOptionsDialog.cpp  include/CQueryWindowOptionsDialog.h include/CConfigDialog.h \
		include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CQueryWindowOptionsDialog.o moc/moc_CQueryWindowOptionsDialog.cpp

tmp/moc_CRegisterServerDialog.o: moc/moc_CRegisterServerDialog.cpp  include/CRegisterServerDialog.h include/CConfigDialog.h \
		include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CRegisterServerDialog.o moc/moc_CRegisterServerDialog.cpp

tmp/moc_CServerAdministrationItem.o: moc/moc_CServerAdministrationItem.cpp  include/CServerAdministrationItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CServerAdministrationItem.o moc/moc_CServerAdministrationItem.cpp

tmp/moc_CServerItem.o: moc/moc_CServerItem.cpp  include/CServerItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CServerItem.o moc/moc_CServerItem.cpp

tmp/moc_CShowDatabaseGroupProperties.o: moc/moc_CShowDatabaseGroupProperties.cpp  include/CShowDatabaseGroupProperties.h include/CProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CShowDatabaseGroupProperties.o moc/moc_CShowDatabaseGroupProperties.cpp

tmp/moc_CShowServerProperties.o: moc/moc_CShowServerProperties.cpp  include/CShowServerProperties.h include/CProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CShowServerProperties.o moc/moc_CShowServerProperties.cpp

tmp/moc_CShowTableGroupProperties.o: moc/moc_CShowTableGroupProperties.cpp  include/CShowTableGroupProperties.h include/CTable.h \
		include/CTableItem.h \
		include/CTableGroupItem.h \
		include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CShowTableGroupProperties.o moc/moc_CShowTableGroupProperties.cpp

tmp/moc_CShowTableProperties.o: moc/moc_CShowTableProperties.cpp  include/CShowTableProperties.h include/CTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CShowTableProperties.o moc/moc_CShowTableProperties.cpp

tmp/moc_CSqlTable.o: moc/moc_CSqlTable.cpp  include/CSqlTable.h include/CQueryTable.h \
		include/CTable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CSqlTable.o moc/moc_CSqlTable.cpp

tmp/moc_CTable.o: moc/moc_CTable.cpp  include/CTable.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTable.o moc/moc_CTable.cpp

tmp/moc_CTableFieldChooser.o: moc/moc_CTableFieldChooser.cpp  include/CTableFieldChooser.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableFieldChooser.o moc/moc_CTableFieldChooser.cpp

tmp/moc_CTableGroupItem.o: moc/moc_CTableGroupItem.cpp  include/CTableGroupItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableGroupItem.o moc/moc_CTableGroupItem.cpp

tmp/moc_CTableItem.o: moc/moc_CTableItem.cpp  include/CTableItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableItem.o moc/moc_CTableItem.cpp

tmp/moc_CTableProperties.o: moc/moc_CTableProperties.cpp  include/CTableProperties.h include/CMyWindow.h \
		include/CProperties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableProperties.o moc/moc_CTableProperties.cpp

tmp/moc_CTableTools.o: moc/moc_CTableTools.cpp  include/CTableTools.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableTools.o moc/moc_CTableTools.cpp

tmp/moc_CTableWindow.o: moc/moc_CTableWindow.cpp  include/CTableWindow.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTableWindow.o moc/moc_CTableWindow.cpp

tmp/moc_CTablesListBox.o: moc/moc_CTablesListBox.cpp  include/CTablesListBox.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTablesListBox.o moc/moc_CTablesListBox.cpp

tmp/moc_CTextDialog.o: moc/moc_CTextDialog.cpp  include/CTextDialog.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTextDialog.o moc/moc_CTextDialog.cpp

tmp/moc_CTextFieldEditor.o: moc/moc_CTextFieldEditor.cpp  include/CTextFieldEditor.h include/CFieldEditorWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CTextFieldEditor.o moc/moc_CTextFieldEditor.cpp

tmp/moc_CToolBar.o: moc/moc_CToolBar.cpp  include/CToolBar.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CToolBar.o moc/moc_CToolBar.cpp

tmp/moc_CUserAdminItem.o: moc/moc_CUserAdminItem.cpp  include/CUserAdminItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CUserAdminItem.o moc/moc_CUserAdminItem.cpp

tmp/moc_CUserAdminWindow.o: moc/moc_CUserAdminWindow.cpp  include/CUserAdminWindow.h include/CMyWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CUserAdminWindow.o moc/moc_CUserAdminWindow.cpp

tmp/moc_CUserItem.o: moc/moc_CUserItem.cpp  include/CUserItem.h include/CDatabaseListViewItem.h \
		include/CDatabaseListView.h \
		include/CToolBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CUserItem.o moc/moc_CUserItem.cpp

tmp/moc_panels.o: moc/moc_panels.cpp  include/panels.h include/CDockWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_panels.o moc/moc_panels.cpp

tmp/moc_shared_menus.o: moc/moc_shared_menus.cpp  include/shared_menus.h include/CPlugin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_shared_menus.o moc/moc_shared_menus.cpp

tmp/moc_CSqlEditor.o: moc/moc_CSqlEditor.cpp  include/CSqlEditor/CSqlEditor.h include/CSqlEditor/editor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CSqlEditor.o moc/moc_CSqlEditor.cpp

tmp/moc_completion.o: moc/moc_completion.cpp  include/CSqlEditor/completion.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_completion.o moc/moc_completion.cpp

tmp/moc_editor.o: moc/moc_editor.cpp  include/CSqlEditor/editor.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_editor.o moc/moc_editor.cpp

tmp/moc_sqlcompletion.o: moc/moc_sqlcompletion.cpp  include/CSqlEditor/sqlcompletion.h include/CSqlEditor/completion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_sqlcompletion.o moc/moc_sqlcompletion.cpp

tmp/moc_CAction.o: moc/moc_CAction.cpp  shared/include/CAction.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CAction.o moc/moc_CAction.cpp

tmp/moc_CMySQL.o: moc/moc_CMySQL.cpp  shared/include/CMySQL.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMySQL.o moc/moc_CMySQL.cpp

tmp/moc_CMySQLCCPlugin.o: moc/moc_CMySQLCCPlugin.cpp  shared/include/CMySQLCCPlugin.h shared/include/CMySQL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMySQLCCPlugin.o moc/moc_CMySQLCCPlugin.cpp

tmp/moc_CMySQLQuery.o: moc/moc_CMySQLQuery.cpp  shared/include/CMySQLQuery.h shared/include/CMySQL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CMySQLQuery.o moc/moc_CMySQLQuery.cpp

tmp/moc_CNullLineEdit.o: moc/moc_CNullLineEdit.cpp  shared/include/CNullLineEdit.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_CNullLineEdit.o moc/moc_CNullLineEdit.cpp

moc/moc_CAboutBox.cpp: $(MOC) include/CAboutBox.h
	$(MOC) include/CAboutBox.h -o moc/moc_CAboutBox.cpp

moc/moc_CAdministrationWindow.cpp: $(MOC) include/CAdministrationWindow.h
	$(MOC) include/CAdministrationWindow.h -o moc/moc_CAdministrationWindow.cpp

moc/moc_CAppConfigDialog.cpp: $(MOC) include/CAppConfigDialog.h
	$(MOC) include/CAppConfigDialog.h -o moc/moc_CAppConfigDialog.cpp

moc/moc_CApplication.cpp: $(MOC) include/CApplication.h
	$(MOC) include/CApplication.h -o moc/moc_CApplication.cpp

moc/moc_CConfigDialog.cpp: $(MOC) include/CConfigDialog.h
	$(MOC) include/CConfigDialog.h -o moc/moc_CConfigDialog.cpp

moc/moc_CConsoleWindow.cpp: $(MOC) include/CConsoleWindow.h
	$(MOC) include/CConsoleWindow.h -o moc/moc_CConsoleWindow.cpp

moc/moc_CCreditsBox.cpp: $(MOC) include/CCreditsBox.h
	$(MOC) include/CCreditsBox.h -o moc/moc_CCreditsBox.cpp

moc/moc_CDatabaseGroupItem.cpp: $(MOC) include/CDatabaseGroupItem.h
	$(MOC) include/CDatabaseGroupItem.h -o moc/moc_CDatabaseGroupItem.cpp

moc/moc_CDatabaseItem.cpp: $(MOC) include/CDatabaseItem.h
	$(MOC) include/CDatabaseItem.h -o moc/moc_CDatabaseItem.cpp

moc/moc_CDatabaseListView.cpp: $(MOC) include/CDatabaseListView.h
	$(MOC) include/CDatabaseListView.h -o moc/moc_CDatabaseListView.cpp

moc/moc_CDatabaseListViewItem.cpp: $(MOC) include/CDatabaseListViewItem.h
	$(MOC) include/CDatabaseListViewItem.h -o moc/moc_CDatabaseListViewItem.cpp

moc/moc_CDockWindow.cpp: $(MOC) include/CDockWindow.h
	$(MOC) include/CDockWindow.h -o moc/moc_CDockWindow.cpp

moc/moc_CFieldEditorWidget.cpp: $(MOC) include/CFieldEditorWidget.h
	$(MOC) include/CFieldEditorWidget.h -o moc/moc_CFieldEditorWidget.cpp

moc/moc_CFieldEditorWindow.cpp: $(MOC) include/CFieldEditorWindow.h
	$(MOC) include/CFieldEditorWindow.h -o moc/moc_CFieldEditorWindow.cpp

moc/moc_CHotKeyEditorDialog.cpp: $(MOC) include/CHotKeyEditorDialog.h
	$(MOC) include/CHotKeyEditorDialog.h -o moc/moc_CHotKeyEditorDialog.cpp

moc/moc_CImageViewer.cpp: $(MOC) include/CImageViewer.h
	$(MOC) include/CImageViewer.h -o moc/moc_CImageViewer.cpp

moc/moc_CInfoDialog.cpp: $(MOC) include/CInfoDialog.h
	$(MOC) include/CInfoDialog.h -o moc/moc_CInfoDialog.cpp

moc/moc_CMDIWindow.cpp: $(MOC) include/CMDIWindow.h
	$(MOC) include/CMDIWindow.h -o moc/moc_CMDIWindow.cpp

moc/moc_CMySQLServer.cpp: $(MOC) include/CMySQLServer.h
	$(MOC) include/CMySQLServer.h -o moc/moc_CMySQLServer.cpp

moc/moc_CMyWindow.cpp: $(MOC) include/CMyWindow.h
	$(MOC) include/CMyWindow.h -o moc/moc_CMyWindow.cpp

moc/moc_CPluginWindow.cpp: $(MOC) include/CPluginWindow.h
	$(MOC) include/CPluginWindow.h -o moc/moc_CPluginWindow.cpp

moc/moc_CProperties.cpp: $(MOC) include/CProperties.h
	$(MOC) include/CProperties.h -o moc/moc_CProperties.cpp

moc/moc_CQueryTable.cpp: $(MOC) include/CQueryTable.h
	$(MOC) include/CQueryTable.h -o moc/moc_CQueryTable.cpp

moc/moc_CQueryWindow.cpp: $(MOC) include/CQueryWindow.h
	$(MOC) include/CQueryWindow.h -o moc/moc_CQueryWindow.cpp

moc/moc_CQueryWindowOptionsDialog.cpp: $(MOC) include/CQueryWindowOptionsDialog.h
	$(MOC) include/CQueryWindowOptionsDialog.h -o moc/moc_CQueryWindowOptionsDialog.cpp

moc/moc_CRegisterServerDialog.cpp: $(MOC) include/CRegisterServerDialog.h
	$(MOC) include/CRegisterServerDialog.h -o moc/moc_CRegisterServerDialog.cpp

moc/moc_CServerAdministrationItem.cpp: $(MOC) include/CServerAdministrationItem.h
	$(MOC) include/CServerAdministrationItem.h -o moc/moc_CServerAdministrationItem.cpp

moc/moc_CServerItem.cpp: $(MOC) include/CServerItem.h
	$(MOC) include/CServerItem.h -o moc/moc_CServerItem.cpp

moc/moc_CShowDatabaseGroupProperties.cpp: $(MOC) include/CShowDatabaseGroupProperties.h
	$(MOC) include/CShowDatabaseGroupProperties.h -o moc/moc_CShowDatabaseGroupProperties.cpp

moc/moc_CShowServerProperties.cpp: $(MOC) include/CShowServerProperties.h
	$(MOC) include/CShowServerProperties.h -o moc/moc_CShowServerProperties.cpp

moc/moc_CShowTableGroupProperties.cpp: $(MOC) include/CShowTableGroupProperties.h
	$(MOC) include/CShowTableGroupProperties.h -o moc/moc_CShowTableGroupProperties.cpp

moc/moc_CShowTableProperties.cpp: $(MOC) include/CShowTableProperties.h
	$(MOC) include/CShowTableProperties.h -o moc/moc_CShowTableProperties.cpp

moc/moc_CSqlTable.cpp: $(MOC) include/CSqlTable.h
	$(MOC) include/CSqlTable.h -o moc/moc_CSqlTable.cpp

moc/moc_CTable.cpp: $(MOC) include/CTable.h
	$(MOC) include/CTable.h -o moc/moc_CTable.cpp

moc/moc_CTableFieldChooser.cpp: $(MOC) include/CTableFieldChooser.h
	$(MOC) include/CTableFieldChooser.h -o moc/moc_CTableFieldChooser.cpp

moc/moc_CTableGroupItem.cpp: $(MOC) include/CTableGroupItem.h
	$(MOC) include/CTableGroupItem.h -o moc/moc_CTableGroupItem.cpp

moc/moc_CTableItem.cpp: $(MOC) include/CTableItem.h
	$(MOC) include/CTableItem.h -o moc/moc_CTableItem.cpp

moc/moc_CTableProperties.cpp: $(MOC) include/CTableProperties.h
	$(MOC) include/CTableProperties.h -o moc/moc_CTableProperties.cpp

moc/moc_CTableTools.cpp: $(MOC) include/CTableTools.h
	$(MOC) include/CTableTools.h -o moc/moc_CTableTools.cpp

moc/moc_CTableWindow.cpp: $(MOC) include/CTableWindow.h
	$(MOC) include/CTableWindow.h -o moc/moc_CTableWindow.cpp

moc/moc_CTablesListBox.cpp: $(MOC) include/CTablesListBox.h
	$(MOC) include/CTablesListBox.h -o moc/moc_CTablesListBox.cpp

moc/moc_CTextDialog.cpp: $(MOC) include/CTextDialog.h
	$(MOC) include/CTextDialog.h -o moc/moc_CTextDialog.cpp

moc/moc_CTextFieldEditor.cpp: $(MOC) include/CTextFieldEditor.h
	$(MOC) include/CTextFieldEditor.h -o moc/moc_CTextFieldEditor.cpp

moc/moc_CToolBar.cpp: $(MOC) include/CToolBar.h
	$(MOC) include/CToolBar.h -o moc/moc_CToolBar.cpp

moc/moc_CUserAdminItem.cpp: $(MOC) include/CUserAdminItem.h
	$(MOC) include/CUserAdminItem.h -o moc/moc_CUserAdminItem.cpp

moc/moc_CUserAdminWindow.cpp: $(MOC) include/CUserAdminWindow.h
	$(MOC) include/CUserAdminWindow.h -o moc/moc_CUserAdminWindow.cpp

moc/moc_CUserItem.cpp: $(MOC) include/CUserItem.h
	$(MOC) include/CUserItem.h -o moc/moc_CUserItem.cpp

moc/moc_panels.cpp: $(MOC) include/panels.h
	$(MOC) include/panels.h -o moc/moc_panels.cpp

moc/moc_shared_menus.cpp: $(MOC) include/shared_menus.h
	$(MOC) include/shared_menus.h -o moc/moc_shared_menus.cpp

moc/moc_CSqlEditor.cpp: $(MOC) include/CSqlEditor/CSqlEditor.h
	$(MOC) include/CSqlEditor/CSqlEditor.h -o moc/moc_CSqlEditor.cpp

moc/moc_completion.cpp: $(MOC) include/CSqlEditor/completion.h
	$(MOC) include/CSqlEditor/completion.h -o moc/moc_completion.cpp

moc/moc_editor.cpp: $(MOC) include/CSqlEditor/editor.h
	$(MOC) include/CSqlEditor/editor.h -o moc/moc_editor.cpp

moc/moc_sqlcompletion.cpp: $(MOC) include/CSqlEditor/sqlcompletion.h
	$(MOC) include/CSqlEditor/sqlcompletion.h -o moc/moc_sqlcompletion.cpp

moc/moc_CAction.cpp: $(MOC) shared/include/CAction.h
	$(MOC) shared/include/CAction.h -o moc/moc_CAction.cpp

moc/moc_CMySQL.cpp: $(MOC) shared/include/CMySQL.h
	$(MOC) shared/include/CMySQL.h -o moc/moc_CMySQL.cpp

moc/moc_CMySQLCCPlugin.cpp: $(MOC) shared/include/CMySQLCCPlugin.h
	$(MOC) shared/include/CMySQLCCPlugin.h -o moc/moc_CMySQLCCPlugin.cpp

moc/moc_CMySQLQuery.cpp: $(MOC) shared/include/CMySQLQuery.h
	$(MOC) shared/include/CMySQLQuery.h -o moc/moc_CMySQLQuery.cpp

moc/moc_CNullLineEdit.cpp: $(MOC) shared/include/CNullLineEdit.h
	$(MOC) shared/include/CNullLineEdit.h -o moc/moc_CNullLineEdit.cpp

####### Install

install:  

uninstall:  

